# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional Cassandra and cassandra-writer. Since these are optional, this file is
# dependent of docker-compose file from <project_root>/docker. In order to run these services, execute command:
# docker compose -f docker/docker-compose.yml -f docker/addons/cassandra-writer/docker-compose.yml up
# from project root.

networks:
  magistrala-base-net:

volumes:
  magistrala-cassandra-volume:

services:
  cassandra:
    image: cassandra:3.11.16
    container_name: magistrala-cassandra
    restart: on-failure
    networks:
      - magistrala-base-net
    ports:
      - ${MG_CASSANDRA_PORT}:${MG_CASSANDRA_PORT}
    volumes:
      - magistrala-cassandra-volume:/var/lib/cassandra

  cassandra-init-keyspace:
    image: cassandra:3.11.16
    depends_on:
      - cassandra
    restart: on-failure
    volumes:
      - ./init.sh:/init.sh
    entrypoint: ["/init.sh"]
    networks:
      - magistrala-base-net

  cassandra-writer:
    image: magistrala/cassandra-writer:${MG_RELEASE_TAG}
    container_name: magistrala-cassandra-writer
    depends_on:
      - cassandra
    restart: on-failure
    environment:
      MG_CASSANDRA_WRITER_LOG_LEVEL: ${MG_CASSANDRA_WRITER_LOG_LEVEL}
      MG_CASSANDRA_WRITER_CONFIG_PATH: ${MG_CASSANDRA_WRITER_CONFIG_PATH}
      MG_CASSANDRA_WRITER_HTTP_HOST: ${MG_CASSANDRA_WRITER_HTTP_HOST}
      MG_CASSANDRA_WRITER_HTTP_PORT: ${MG_CASSANDRA_WRITER_HTTP_PORT}
      MG_CASSANDRA_WRITER_HTTP_SERVER_CERT: ${MG_CASSANDRA_WRITER_HTTP_SERVER_CERT}
      MG_CASSANDRA_WRITER_HTTP_SERVER_KEY: ${MG_CASSANDRA_WRITER_HTTP_SERVER_KEY}
      MG_CASSANDRA_PORT: ${MG_CASSANDRA_PORT}
      MG_CASSANDRA_CLUSTER: ${MG_CASSANDRA_CLUSTER}
      MG_CASSANDRA_KEYSPACE: ${MG_CASSANDRA_KEYSPACE}
      MG_CASSANDRA_USER: ${MG_CASSANDRA_USER}
      MG_CASSANDRA_PASS: ${MG_CASSANDRA_PASS}
      MG_MESSAGE_BROKER_URL: ${MG_MESSAGE_BROKER_URL}
      MG_JAEGER_URL: ${MG_JAEGER_URL}
      MG_JAEGER_TRACE_RATIO: ${MG_JAEGER_TRACE_RATIO}
      MG_SEND_TELEMETRY: ${MG_SEND_TELEMETRY}
      MG_CASSANDRA_WRITER_INSTANCE_ID: ${MG_CASSANDRA_WRITER_INSTANCE_ID}
    ports:
      - ${MG_CASSANDRA_WRITER_HTTP_PORT}:${MG_CASSANDRA_WRITER_HTTP_PORT}
    networks:
      - magistrala-base-net
    volumes:
      - ./config.toml:/config.toml
